[package]
name = "todo"
version.workspace = true
edition = "2024"
description = "Task management for Zero"
license.workspace = true

[lints]
workspace = true

[dependencies]
foundation = { path = "../foundation" }
etchdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
